### PR TITLE
Feat/speakers

### PR DESCRIPTION
**Pull request by chotixity**
## Type of Change
- Fixed a bug on go router subroute(routes were breaking because of the recent merge adding a leading / which is not required in subroutes)
- Makes the badge to display dynamic speaker list length

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

## Test Changes on Device
You can download your APK from Firebase App Distribution once this PR builds successfully via the following link: https://appdistribution.firebase.dev/i/c796669942f8a811

### CODE REVIEW

**Comment by chotixity** [comment]
For this to work this change has to override the already changes causing the conflicts @MillerAdulu

**Comment by MillerAdulu** [comment]
@chotixity,

The fixes mentioned here should be resolved on #69. 

Kindly checkout to `main` on your local, pull the `main` branch and run the project to see if there's anything that was missed out.

**Comment by chotixity** [comment]
They're all taken care of

**Comment by chotixity** [comment]
taken care of on #69

**Pull request closed without merging**
