### PR TITLE
:bug: fixed overflows on the speaker details  screen

### PR DESCRIPTION
**Pull request by chotixity**
## Description

Fixed overflows on the speaker details page

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

## Test Changes on Device
You can download your APK from Firebase App Distribution once this PR builds successfully via the following link: https://appdistribution.firebase.dev/i/c796669942f8a811

### CODE REVIEW

**Comment by MillerAdulu** [comment]
@chotixity,

Kindly share a screenshot of how the screen looks like now on the description.

**Comment by MillerAdulu** [comment]
simulator_screenshot_731A216B-E2EF-41CC-AAC7-1E1C90CE97CB

Hi @chotixity,

I have run your branch on my local and it doesn't adhere to the design. The idea behind the initial implementation was to allow the overflow to happen so that half the image is in the navbar and the other half is in the body. In release mode, overflow errors don't cause a crash so the UI would display just fine.

**Comment by chotixity** [comment]
Alright, for longer profiles case in point Kai mwanyumba in the design, there is a bottom overflow. You can look to fix that too in your branch.

**Comment by MillerAdulu** [comment]
@chotixity,

I have moved away from that branch, do you mind sharing a screenshot here? We can discuss the approach here to see the best way forward.

**Comment by chotixity** [comment]
Screenshot_20240815-221548
This is running on my branch. You can the page is overflowing, adding singlechildscrollview should fix it

**Comment by MillerAdulu** [comment]
I have seen what you mean. It wasn't clear before. Making corrections then pushing. I am currently working on #75 so I have made that slight change on that PR. Here's how it looks ATM.

The main issue with your approach is that it doesn't capture how the image of the speaker can be in between the top nav and the main body. 

https://github.com/user-attachments/assets/01b5b1c8-7a5d-4777-b779-617f17bef730

**Comment by MillerAdulu** [comment]
Resolved in #80

**Pull request closed without merging**
