### PR TITLE
Adaptive layouts

### PR DESCRIPTION
**Pull request by chotixity**
## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

## Test Changes on Device
You can download your APK from Firebase App Distribution once this PR builds successfully via the following link: https://appdistribution.firebase.dev/i/c796669942f8a811

### CODE REVIEW

**Comment by chotixity** [comment]
@MillerAdulu you can run it on ypur device to see if the images look pixelated, my tablet imegoma kuload the images

**Review by MillerAdulu — CHANGES_REQUESTED** [review]
Please make the following changes;

`lib/features/home/widgets/speaker_home_card.dart:99`, please change
```dart
speakers.take(5).length to speakers.take(10).length
```
`lib/features/home/cubit/fetch_speakers_cubit.dart:33,46`
```dart
extras: localSpeakers.length - 5 to extras: localSpeakers.length - 10
```

`lib/features/home/widgets/sessions_card.dart:109`
```dart
sessions.take(5).length, to sessions.take(10).length
```
`lib/features/home/cubit/fetch_sessions_cubit.dart:38,55`
```dart
extras: localSessions.length - 5 to extras: localSessions.length - 10
```

**Comment by chotixity** [comment]
@MillerAdulu the changes are now pushed, same PR

**Review by MillerAdulu — CHANGES_REQUESTED** [review]
Issues
- Session Details page doesn't open on a tablet, there's a `The _RenderLayoutBuilder class does not support dry layout.` error and the entire app becomes unusable requiring a restart
- Speaker cards on the home page should be square, currently, they are rectangular (landscape) so the images of the speakers are sliced
- Sponsor and organised by logos look too large on the home page with respect to other content
- The feed page images don't cover the entire width

Notes
- Speaker details page is splendid


Identified on tablet mode @chotixity. Please also merge `main` into this branch.

**Comment by MillerAdulu** [comment]
@chotixity,

I am assuming that this was an error on your end with the merge and that you haven't lost the `auto_text`  changes. I have them on my local in case you nuked your branch. I can make a branch for you to finalise the PR.

**Comment by chotixity** [comment]
I have lost all my changes, you could help me with reuplpoading the branch

**Comment by MillerAdulu** [comment]
https://github.com/droidconKE/flutterconKEApp/tree/recon/layouts

@chotixity,

Here is the branch with the changes I had pulled on my local to test the look. You can restart the changes from here https://github.com/droidconKE/flutterconKEApp/pull/114#pullrequestreview-2262469971. I have also merged `main` into that branch so you should be able to proceed without issues.

**Pull request closed without merging**
